"""
comps_dupont.py — Comps + DuPont module for the M&A screener.

For the shortlisted (top-ranked) companies, this module answers two
questions the composite score alone can't:

  1. COMPS: is this company actually cheap/expensive relative to its
     sector peers, in plain terms (not just a percentile score)?
  2. DUPONT: WHY does this company have the ROE it has? A high ROE driven
     by genuine operating efficiency (margin, turnover) is a different
     story than one driven purely by leverage — this is the quality-of-
     earnings check that a raw composite score can't tell you.

DuPont identity used (standard 3-factor decomposition):
    ROE = Net Margin  x  Asset Turnover  x  Equity Multiplier
where Equity Multiplier = Total Assets / Total Equity
    (approximated here as (Total Debt + Total Equity) / Total Equity,
     since we don't pull total assets directly from yfinance — this is
     a reasonable proxy, not a perfect one, and is labeled as such in
     the output rather than presented as exact.)

Usage:
    python -m src.comps_dupont
"""

import logging
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def load_scored_universe(path: str = "data/processed/scored_universe.csv") -> pd.DataFrame:
    df = pd.read_csv(path)
    if df.empty:
        raise ValueError(f"{path} is empty — run the scoring step first.")
    return df


def compute_sector_comps(df: pd.DataFrame) -> pd.DataFrame:
    """For each company, benchmark its key multiples against its sector's
    median and flag whether it's trading cheap or rich relative to peers —
    in plain terms, not just a percentile score."""
    comps = df.copy()

    for metric in ["trailing_pe", "ev_to_ebitda"]:
        if metric not in comps.columns:
            continue
        sector_median = comps.groupby("sector")[metric].transform("median")
        comps[f"{metric}_vs_sector_median"] = comps[metric] - sector_median
        comps[f"{metric}_pct_vs_sector_median"] = (
            (comps[metric] - sector_median) / sector_median
        )

    def label_valuation(row):
        pe_diff = row.get("trailing_pe_pct_vs_sector_median")
        if pd.isna(pe_diff):
            return "insufficient data"
        if pe_diff <= -0.15:
            return "cheap vs sector"
        if pe_diff >= 0.15:
            return "rich vs sector"
        return "in line with sector"

    comps["valuation_label"] = comps.apply(label_valuation, axis=1)
    return comps


def compute_dupont(df: pd.DataFrame) -> pd.DataFrame:
    """3-factor DuPont decomposition: ROE = net margin x asset turnover x
    equity multiplier. Flags negative/zero equity explicitly rather than
    computing a nonsensical ratio, matching the same discipline the
    cleaning layer already applies upstream."""
    dupont = df.copy()

    required = ["total_debt", "total_equity", "net_margin", "asset_turnover", "return_on_equity"]
    missing_cols = [c for c in required if c not in dupont.columns]
    if missing_cols:
        raise ValueError(
            f"comps_dupont.py requires these columns from the scoring step, "
            f"but they're missing from the input: {missing_cols}. "
            f"This usually means scored_universe.csv was generated by an "
            f"older version of src/scoring.py — re-run `python -m src.scoring` "
            f"with the current version, then retry this module."
        )

    if "total_debt" in dupont.columns and "total_equity" in dupont.columns:
        valid_equity = dupont["total_equity"].notna() & (dupont["total_equity"] > 0)
        raw_multiplier = (dupont["total_debt"].fillna(0) + dupont["total_equity"]) / dupont["total_equity"]
        dupont["equity_multiplier"] = raw_multiplier.where(valid_equity)
        if (~valid_equity).any():
            dupont["dupont_flag"] = pd.Series(
                ["negative or missing equity — equity multiplier not computed" if not v else None for v in valid_equity],
                index=dupont.index,
            )
    else:
        dupont["equity_multiplier"] = float("nan")
        logger.warning("total_debt/total_equity not found in scored data — equity multiplier unavailable")

    # dupont_implied_roe only needs the three DuPont inputs — it should
    # compute even when reported ROE is missing (e.g. SHREECEM.NS, where
    # yfinance never returned a return_on_equity value at all). This is
    # precisely the recovery case the module exists for: deriving a real
    # ROE estimate from decomposed fundamentals when the direct figure
    # is missing, rather than leaving the company with no ROE signal.
    #
    # Using .where() rather than .loc[mask, col] = ... assignment: the
    # latter throws a pandas dtype error on some pandas versions when the
    # mask is entirely False or entirely True on a small/single-row frame
    # (a real edge case hit during testing) — .where() computes the full
    # vectorized expression first and masks after, sidestepping that
    # assignment-path quirk entirely.
    can_compute_implied = (
        dupont["net_margin"].notna()
        & dupont["asset_turnover"].notna()
        & dupont["equity_multiplier"].notna()
    )
    raw_implied_roe = dupont["net_margin"] * dupont["asset_turnover"] * dupont["equity_multiplier"]
    dupont["dupont_implied_roe"] = raw_implied_roe.where(can_compute_implied)

    # The gap check is a separate, stricter comparison: it ADDITIONALLY
    # needs reported ROE to exist, since it's cross-checking implied vs
    # reported. A missing reported ROE means "no gap to check" (NaN),
    # not "can't compute implied ROE" — those are different questions.
    can_check_gap = can_compute_implied & dupont["return_on_equity"].notna()
    raw_gap = dupont["dupont_implied_roe"] - dupont["return_on_equity"]
    dupont["dupont_vs_reported_roe_gap"] = raw_gap.where(can_check_gap)

    return dupont


def build_report(
    scored_path: str = "data/processed/scored_universe.csv",
    output_dir: str = "data/processed",
    top_n: int = 10,
) -> pd.DataFrame:
    df = load_scored_universe(scored_path)
    shortlist = df[df["rank"] <= top_n].copy()

    comps = compute_sector_comps(shortlist)
    full = compute_dupont(comps)

    output_cols = [
        "rank", "ticker", "sector", "sector_rank", "composite_score",
        "trailing_pe", "trailing_pe_vs_sector_median", "valuation_label",
        "return_on_equity", "net_margin", "asset_turnover", "equity_multiplier",
        "dupont_implied_roe", "dupont_vs_reported_roe_gap",
    ]
    output_cols = [c for c in output_cols if c in full.columns]
    result = full[output_cols]

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    out_path = Path(output_dir) / "comps_dupont_report.csv"
    result.to_csv(out_path, index=False)
    logger.info(f"Comps + DuPont report for top {top_n} -> {out_path}")

    large_gaps = result[result["dupont_vs_reported_roe_gap"].abs() > 0.05] if "dupont_vs_reported_roe_gap" in result.columns else pd.DataFrame()
    if len(large_gaps) > 0:
        logger.warning(
            f"{len(large_gaps)} companies have a DuPont-implied ROE that "
            f"diverges >5pp from reported ROE (possible data inconsistency, "
            f"worth a manual check): {large_gaps['ticker'].tolist()}"
        )

    return result


if __name__ == "__main__":
    result = build_report()
    print(f"\nDone. Comps + DuPont report built for {len(result)} shortlisted companies.")
    print("\n" + result.to_string(index=False))
